In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../artifacts/data.csv")
df.head()

,Patient ID,Age,Gender,Vaccination Date,Vaccine Dose,Pre-existing Conditions,Heart Attack Date,Heart Attack Related to Vaccine,Location,Blood Pressure,Cholesterol Level,BMI,Smoking History,Diabetes Status
0,879,82,Male,2022-06-06,2nd Dose,Asthma,NaN,False,San Diego,Very Low,180,35.0,No,Yes
1,492,48,Female,2020-09-11,Booster,Heart Disease,NaN,False,Charlotte,Low,220,22.5,No,Yes
2,146,80,Male,2023-02-03,1st Dose,Hypertension,NaN,False,San Diego,Very High,210,25.6,Yes,Yes
3,739,74,Male,2020-12-29,Booster,Diabetes,2021-01-10,True,Fort Worth,High,275,20.8,Yes,No
4,209,30,Male,2020-05-29,2nd Dose,Asthma,NaN,False,San Jose,High,200,35.3,Yes,Yes

In [3]:
df[['Blood Pressure', 'Diabetes Status', 'Gender', 'Heart Attack Related to Vaccine', 'Location', 'Pre-existing Conditions', 'Smoking History', 'Vaccine Dose']]

,Blood Pressure,Diabetes Status,Gender,Heart Attack Related to Vaccine,Location,Pre-existing Conditions,Smoking History,Vaccine Dose
0,Very Low,Yes,Male,False,San Diego,Asthma,No,2nd Dose
1,Low,Yes,Female,False,Charlotte,Heart Disease,No,Booster
2,Very High,Yes,Male,False,San Diego,Hypertension,Yes,1st Dose
3,High,No,Male,True,Fort Worth,Diabetes,Yes,Booster
4,High,Yes,Male,False,San Jose,Asthma,Yes,2nd Dose
...,...,...,...,...,...,...,...,...
9995,Very Low,Yes,Male,True,San Antonio,Diabetes,No,Booster
9996,Very Low,Yes,Female,False,Indianapolis,NaN,No,1st Dose
9997,Normal,Yes,Male,True,Chicago,NaN,Yes,1st Dose
9998,Low,Yes,Female,True,New York,Hypertension,No,2nd Dose
9999,High,No,Female,False,Denver,NaN,No,1st Dose

In [4]:
df.select_dtypes(include=["number"]).columns.difference(['User_ID'])

Index(['Age', 'BMI', 'Cholesterol Level', 'Patient ID'], dtype='object')

In [5]:
df['Heart Attack Date'] = pd.to_datetime(df['Heart Attack Date'], errors='coerce')
df['Heart Attack Date'].apply(lambda x: 1 if x else 0)

0       1
1       1
2       1
3       1
4       1
       ..
9995    1
9996    1
9997    1
9998    1
9999    1
Name: Heart Attack Date, Length: 10000, dtype: int64

In [ ]:
df['Heart Attack Related to Vaccine'].astype(int).sum()

0       0
1       0
2       0
3       1
4       0
       ..
9995    1
9996    0
9997    1
9998    1
9999    0
Name: Heart Attack Related to Vaccine, Length: 10000, dtype: int64